//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiceClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiceClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_10_1 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_10_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_10_2 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_10_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_10_3 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_10_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_100_1 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_100_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_100_2 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_100_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_100_3 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_100_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_5_1 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_5_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_5_2 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_5_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_5_3 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_5_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_50_1 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_50_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_50_2 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_50_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_50_3 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_50_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_500_1 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_500_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_500_2 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_500_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_500_3 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_500_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chip10 {
            get {
                object obj = ResourceManager.GetObject("Chip10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chip100 {
            get {
                object obj = ResourceManager.GetObject("Chip100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chip5 {
            get {
                object obj = ResourceManager.GetObject("Chip5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chip50 {
            get {
                object obj = ResourceManager.GetObject("Chip50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chip500 {
            get {
                object obj = ResourceManager.GetObject("Chip500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DanPanel {
            get {
                object obj = ResourceManager.GetObject("DanPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DaPanel {
            get {
                object obj = ResourceManager.GetObject("DaPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dice1 {
            get {
                object obj = ResourceManager.GetObject("dice1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dice2 {
            get {
                object obj = ResourceManager.GetObject("dice2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dice3 {
            get {
                object obj = ResourceManager.GetObject("dice3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dice4 {
            get {
                object obj = ResourceManager.GetObject("dice4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dice5 {
            get {
                object obj = ResourceManager.GetObject("dice5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dice6 {
            get {
                object obj = ResourceManager.GetObject("dice6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon dicegame {
            get {
                object obj = ResourceManager.GetObject("dicegame", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DiceGameBackground {
            get {
                object obj = ResourceManager.GetObject("DiceGameBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num0 {
            get {
                object obj = ResourceManager.GetObject("Num0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num1 {
            get {
                object obj = ResourceManager.GetObject("Num1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num2 {
            get {
                object obj = ResourceManager.GetObject("Num2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num3 {
            get {
                object obj = ResourceManager.GetObject("Num3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num4 {
            get {
                object obj = ResourceManager.GetObject("Num4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num5 {
            get {
                object obj = ResourceManager.GetObject("Num5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num6 {
            get {
                object obj = ResourceManager.GetObject("Num6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num7 {
            get {
                object obj = ResourceManager.GetObject("Num7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num8 {
            get {
                object obj = ResourceManager.GetObject("Num8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Num9 {
            get {
                object obj = ResourceManager.GetObject("Num9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] SCORE_10 {
            get {
                object obj = ResourceManager.GetObject("SCORE_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SCORE_100 {
            get {
                object obj = ResourceManager.GetObject("SCORE_100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SCORE_5 {
            get {
                object obj = ResourceManager.GetObject("SCORE_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SCORE_50 {
            get {
                object obj = ResourceManager.GetObject("SCORE_50", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SCORE_500 {
            get {
                object obj = ResourceManager.GetObject("SCORE_500", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShuangPanel {
            get {
                object obj = ResourceManager.GetObject("ShuangPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VolumnClose {
            get {
                object obj = ResourceManager.GetObject("VolumnClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VolumnOpen {
            get {
                object obj = ResourceManager.GetObject("VolumnOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap XiaoPanel {
            get {
                object obj = ResourceManager.GetObject("XiaoPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowSqure {
            get {
                object obj = ResourceManager.GetObject("YellowSqure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
