//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SicboClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SicboClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ADD_GOLD {
            get {
                return ResourceManager.GetStream("ADD_GOLD", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ADD_GOLD_EX {
            get {
                return ResourceManager.GetStream("ADD_GOLD_EX", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Ani_1 {
            get {
                object obj = ResourceManager.GetObject("Ani_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_10 {
            get {
                object obj = ResourceManager.GetObject("Ani_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_11 {
            get {
                object obj = ResourceManager.GetObject("Ani_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_12 {
            get {
                object obj = ResourceManager.GetObject("Ani_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_13 {
            get {
                object obj = ResourceManager.GetObject("Ani_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_14 {
            get {
                object obj = ResourceManager.GetObject("Ani_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_15 {
            get {
                object obj = ResourceManager.GetObject("Ani_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_16 {
            get {
                object obj = ResourceManager.GetObject("Ani_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_17 {
            get {
                object obj = ResourceManager.GetObject("Ani_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_18 {
            get {
                object obj = ResourceManager.GetObject("Ani_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_2 {
            get {
                object obj = ResourceManager.GetObject("Ani_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_3 {
            get {
                object obj = ResourceManager.GetObject("Ani_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_4 {
            get {
                object obj = ResourceManager.GetObject("Ani_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_5 {
            get {
                object obj = ResourceManager.GetObject("Ani_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_6 {
            get {
                object obj = ResourceManager.GetObject("Ani_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_7 {
            get {
                object obj = ResourceManager.GetObject("Ani_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_8 {
            get {
                object obj = ResourceManager.GetObject("Ani_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ani_9 {
            get {
                object obj = ResourceManager.GetObject("Ani_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream BACK_GROUND {
            get {
                return ResourceManager.GetStream("BACK_GROUND", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap BT_APPLY_BANKER {
            get {
                object obj = ResourceManager.GetObject("BT_APPLY_BANKER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_CANCEL_BANKER {
            get {
                object obj = ResourceManager.GetObject("BT_CANCEL_BANKER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_DOWN {
            get {
                object obj = ResourceManager.GetObject("BT_DOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_100 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_1000 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_1000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_10000 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_10000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_100000 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_100000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_1000000 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_1000000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_500000 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_500000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_JETTON_5000000 {
            get {
                object obj = ResourceManager.GetObject("BT_JETTON_5000000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_UP {
            get {
                object obj = ResourceManager.GetObject("BT_UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CARD_TYPE {
            get {
                object obj = ResourceManager.GetObject("CARD_TYPE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CHANGE_BANKER {
            get {
                object obj = ResourceManager.GetObject("CHANGE_BANKER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream CHEER1 {
            get {
                return ResourceManager.GetStream("CHEER1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream CHEER2 {
            get {
                return ResourceManager.GetStream("CHEER2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream CHEER3 {
            get {
                return ResourceManager.GetStream("CHEER3", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream END_DRAW {
            get {
                return ResourceManager.GetStream("END_DRAW", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream END_LOST {
            get {
                return ResourceManager.GetStream("END_LOST", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream END_WIN {
            get {
                return ResourceManager.GetStream("END_WIN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FIRE_EFFECT {
            get {
                object obj = ResourceManager.GetObject("FIRE_EFFECT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FRAME_WIN {
            get {
                object obj = ResourceManager.GetObject("FRAME_WIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GAME_END {
            get {
                object obj = ResourceManager.GetObject("GAME_END", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream GAME_START {
            get {
                return ResourceManager.GetStream("GAME_START", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GIFT_INTHEAIR {
            get {
                object obj = ResourceManager.GetObject("GIFT_INTHEAIR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JETTOM_VIEW {
            get {
                object obj = ResourceManager.GetObject("JETTOM_VIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JETTOM_VIEW1 {
            get {
                object obj = ResourceManager.GetObject("JETTOM_VIEW1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ME_BANKER {
            get {
                object obj = ResourceManager.GetObject("ME_BANKER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ME_SCORE_NUMBER {
            get {
                object obj = ResourceManager.GetObject("ME_SCORE_NUMBER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NO_BANKER {
            get {
                object obj = ResourceManager.GetObject("NO_BANKER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] NORMAL {
            get {
                object obj = ResourceManager.GetObject("NORMAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_00 {
            get {
                object obj = ResourceManager.GetObject("one_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_01 {
            get {
                object obj = ResourceManager.GetObject("one_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_02 {
            get {
                object obj = ResourceManager.GetObject("one_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_03 {
            get {
                object obj = ResourceManager.GetObject("one_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_04 {
            get {
                object obj = ResourceManager.GetObject("one_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_05 {
            get {
                object obj = ResourceManager.GetObject("one_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_06 {
            get {
                object obj = ResourceManager.GetObject("one_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_07 {
            get {
                object obj = ResourceManager.GetObject("one_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_08 {
            get {
                object obj = ResourceManager.GetObject("one_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_09 {
            get {
                object obj = ResourceManager.GetObject("one_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_10 {
            get {
                object obj = ResourceManager.GetObject("one_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_11 {
            get {
                object obj = ResourceManager.GetObject("one_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_12 {
            get {
                object obj = ResourceManager.GetObject("one_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_13 {
            get {
                object obj = ResourceManager.GetObject("one_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_14 {
            get {
                object obj = ResourceManager.GetObject("one_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_15 {
            get {
                object obj = ResourceManager.GetObject("one_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_16 {
            get {
                object obj = ResourceManager.GetObject("one_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_17 {
            get {
                object obj = ResourceManager.GetObject("one_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_18 {
            get {
                object obj = ResourceManager.GetObject("one_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_19 {
            get {
                object obj = ResourceManager.GetObject("one_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_20 {
            get {
                object obj = ResourceManager.GetObject("one_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_21 {
            get {
                object obj = ResourceManager.GetObject("one_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_22 {
            get {
                object obj = ResourceManager.GetObject("one_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_23 {
            get {
                object obj = ResourceManager.GetObject("one_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_24 {
            get {
                object obj = ResourceManager.GetObject("one_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_25 {
            get {
                object obj = ResourceManager.GetObject("one_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_26 {
            get {
                object obj = ResourceManager.GetObject("one_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_27 {
            get {
                object obj = ResourceManager.GetObject("one_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_28 {
            get {
                object obj = ResourceManager.GetObject("one_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_29 {
            get {
                object obj = ResourceManager.GetObject("one_29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_30 {
            get {
                object obj = ResourceManager.GetObject("one_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_31 {
            get {
                object obj = ResourceManager.GetObject("one_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_32 {
            get {
                object obj = ResourceManager.GetObject("one_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_33 {
            get {
                object obj = ResourceManager.GetObject("one_33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_34 {
            get {
                object obj = ResourceManager.GetObject("one_34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_35 {
            get {
                object obj = ResourceManager.GetObject("one_35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_36 {
            get {
                object obj = ResourceManager.GetObject("one_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_37 {
            get {
                object obj = ResourceManager.GetObject("one_37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_38 {
            get {
                object obj = ResourceManager.GetObject("one_38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_39 {
            get {
                object obj = ResourceManager.GetObject("one_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_40 {
            get {
                object obj = ResourceManager.GetObject("one_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_41 {
            get {
                object obj = ResourceManager.GetObject("one_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_42 {
            get {
                object obj = ResourceManager.GetObject("one_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_43 {
            get {
                object obj = ResourceManager.GetObject("one_43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_44 {
            get {
                object obj = ResourceManager.GetObject("one_44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_45 {
            get {
                object obj = ResourceManager.GetObject("one_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_46 {
            get {
                object obj = ResourceManager.GetObject("one_46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_47 {
            get {
                object obj = ResourceManager.GetObject("one_47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_48 {
            get {
                object obj = ResourceManager.GetObject("one_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_49 {
            get {
                object obj = ResourceManager.GetObject("one_49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_50 {
            get {
                object obj = ResourceManager.GetObject("one_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap one_51 {
            get {
                object obj = ResourceManager.GetObject("one_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OPEN_BANK {
            get {
                object obj = ResourceManager.GetObject("OPEN_BANK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] SCORE_100 {
            get {
                object obj = ResourceManager.GetObject("SCORE_100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SCORE_1000 {
            get {
                object obj = ResourceManager.GetObject("SCORE_1000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SCORE_10000 {
            get {
                object obj = ResourceManager.GetObject("SCORE_10000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SCORE_100000 {
            get {
                object obj = ResourceManager.GetObject("SCORE_100000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SCORE_1000000 {
            get {
                object obj = ResourceManager.GetObject("SCORE_1000000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SCORE_500 {
            get {
                object obj = ResourceManager.GetObject("SCORE_500", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SCORE_50000 {
            get {
                object obj = ResourceManager.GetObject("SCORE_50000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SCORE_500000 {
            get {
                object obj = ResourceManager.GetObject("SCORE_500000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SCORE_5000000 {
            get {
                object obj = ResourceManager.GetObject("SCORE_5000000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SCORE_NUMBER {
            get {
                object obj = ResourceManager.GetObject("SCORE_NUMBER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SICBO_DESKTOP {
            get {
                object obj = ResourceManager.GetObject("SICBO_DESKTOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SICBO_EFFECT_BACK {
            get {
                object obj = ResourceManager.GetObject("SICBO_EFFECT_BACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SICBO_EFFECT_DESKTOP {
            get {
                object obj = ResourceManager.GetObject("SICBO_EFFECT_DESKTOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SICBO_EFFECT_INMIDAIR {
            get {
                object obj = ResourceManager.GetObject("SICBO_EFFECT_INMIDAIR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SICBO_EFFECT_NORMAL {
            get {
                object obj = ResourceManager.GetObject("SICBO_EFFECT_NORMAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SICBO_EFFECT_RESULT {
            get {
                object obj = ResourceManager.GetObject("SICBO_EFFECT_RESULT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SICBO_EPLAN {
            get {
                object obj = ResourceManager.GetObject("SICBO_EPLAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SICBO_IN_MIDAIR {
            get {
                object obj = ResourceManager.GetObject("SICBO_IN_MIDAIR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SICBO_IN_THE_AIR {
            get {
                object obj = ResourceManager.GetObject("SICBO_IN_THE_AIR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SICBO_IN_THE_AIR1 {
            get {
                object obj = ResourceManager.GetObject("SICBO_IN_THE_AIR1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SICBO_NUM {
            get {
                object obj = ResourceManager.GetObject("SICBO_NUM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SICBO_NUMBER_DOT {
            get {
                object obj = ResourceManager.GetObject("SICBO_NUMBER_DOT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SICBO_PLAN {
            get {
                object obj = ResourceManager.GetObject("SICBO_PLAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SICBO_POINT {
            get {
                object obj = ResourceManager.GetObject("SICBO_POINT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TIME_FLAG {
            get {
                object obj = ResourceManager.GetObject("TIME_FLAG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream TIME_WARIMG {
            get {
                return ResourceManager.GetStream("TIME_WARIMG", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap USER_PROMPT {
            get {
                object obj = ResourceManager.GetObject("USER_PROMPT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VIEW_BACK {
            get {
                object obj = ResourceManager.GetObject("VIEW_BACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VIEW_FILL {
            get {
                object obj = ResourceManager.GetObject("VIEW_FILL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_FLAGS {
            get {
                object obj = ResourceManager.GetObject("WIN_FLAGS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
