//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FishClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BT_ANIMAL_BEAST {
            get {
                object obj = ResourceManager.GetObject("BT_ANIMAL_BEAST", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_ANIMAL_BIRD {
            get {
                object obj = ResourceManager.GetObject("BT_ANIMAL_BIRD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_ANIMAL_EAGLE {
            get {
                object obj = ResourceManager.GetObject("BT_ANIMAL_EAGLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_ANIMAL_GOLD_SHARK {
            get {
                object obj = ResourceManager.GetObject("BT_ANIMAL_GOLD_SHARK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_ANIMAL_LION {
            get {
                object obj = ResourceManager.GetObject("BT_ANIMAL_LION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_ANIMAL_MONKEY {
            get {
                object obj = ResourceManager.GetObject("BT_ANIMAL_MONKEY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_ANIMAL_PANDA {
            get {
                object obj = ResourceManager.GetObject("BT_ANIMAL_PANDA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_ANIMAL_PEACOCK {
            get {
                object obj = ResourceManager.GetObject("BT_ANIMAL_PEACOCK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_ANIMAL_PIGEON {
            get {
                object obj = ResourceManager.GetObject("BT_ANIMAL_PIGEON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_ANIMAL_RABBIT {
            get {
                object obj = ResourceManager.GetObject("BT_ANIMAL_RABBIT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_ANIMAL_SLIVER_SHARK {
            get {
                object obj = ResourceManager.GetObject("BT_ANIMAL_SLIVER_SHARK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_ANIMAL_SWALLOW {
            get {
                object obj = ResourceManager.GetObject("BT_ANIMAL_SWALLOW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_OPERATION_CANCEL {
            get {
                object obj = ResourceManager.GetObject("BT_OPERATION_CANCEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_OPERATION_RENEWAL {
            get {
                object obj = ResourceManager.GetObject("BT_OPERATION_RENEWAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_OPERATION_SWITCH {
            get {
                object obj = ResourceManager.GetObject("BT_OPERATION_SWITCH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Eagle {
            get {
                object obj = ResourceManager.GetObject("Eagle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_1 {
            get {
                object obj = ResourceManager.GetObject("FISH_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_2 {
            get {
                object obj = ResourceManager.GetObject("FISH_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_3 {
            get {
                object obj = ResourceManager.GetObject("FISH_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_4 {
            get {
                object obj = ResourceManager.GetObject("FISH_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_5 {
            get {
                object obj = ResourceManager.GetObject("FISH_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_6 {
            get {
                object obj = ResourceManager.GetObject("FISH_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_BACK_I {
            get {
                object obj = ResourceManager.GetObject("FISH_BACK_I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_BACK_II {
            get {
                object obj = ResourceManager.GetObject("FISH_BACK_II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_BACK_III {
            get {
                object obj = ResourceManager.GetObject("FISH_BACK_III", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_BACK_IV {
            get {
                object obj = ResourceManager.GetObject("FISH_BACK_IV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_BACK_V {
            get {
                object obj = ResourceManager.GetObject("FISH_BACK_V", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_BACK_VI {
            get {
                object obj = ResourceManager.GetObject("FISH_BACK_VI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_BACK_VII {
            get {
                object obj = ResourceManager.GetObject("FISH_BACK_VII", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_BULLET {
            get {
                object obj = ResourceManager.GetObject("FISH_BULLET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_CANNON {
            get {
                object obj = ResourceManager.GetObject("FISH_CANNON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_GUN {
            get {
                object obj = ResourceManager.GetObject("FISH_GUN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FISH_NET {
            get {
                object obj = ResourceManager.GetObject("FISH_NET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FLICKER_GREEN {
            get {
                object obj = ResourceManager.GetObject("FLICKER_GREEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FLICKER_RED {
            get {
                object obj = ResourceManager.GetObject("FLICKER_RED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FLICKER_YELLOW {
            get {
                object obj = ResourceManager.GetObject("FLICKER_YELLOW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Goldshark {
            get {
                object obj = ResourceManager.GetObject("Goldshark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HISTORY_ANIMAL {
            get {
                object obj = ResourceManager.GetObject("HISTORY_ANIMAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Idle {
            get {
                object obj = ResourceManager.GetObject("Idle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Idle2 {
            get {
                object obj = ResourceManager.GetObject("Idle2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KEEP_OUT {
            get {
                object obj = ResourceManager.GetObject("KEEP_OUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KEEP_OUT_ON_BET {
            get {
                object obj = ResourceManager.GetObject("KEEP_OUT_ON_BET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Laser {
            get {
                object obj = ResourceManager.GetObject("Laser", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LASER_I {
            get {
                object obj = ResourceManager.GetObject("LASER_I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LASER_II {
            get {
                object obj = ResourceManager.GetObject("LASER_II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Lion {
            get {
                object obj = ResourceManager.GetObject("Lion", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MAIN_ANIMALS {
            get {
                object obj = ResourceManager.GetObject("MAIN_ANIMALS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MAIN_ANIMALS_BACK {
            get {
                object obj = ResourceManager.GetObject("MAIN_ANIMALS_BACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MAIN_BACK {
            get {
                object obj = ResourceManager.GetObject("MAIN_BACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Monkey {
            get {
                object obj = ResourceManager.GetObject("Monkey", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NUMBER_BLUE {
            get {
                object obj = ResourceManager.GetObject("NUMBER_BLUE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NUMBER_GREEN {
            get {
                object obj = ResourceManager.GetObject("NUMBER_GREEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NUMBER_RED {
            get {
                object obj = ResourceManager.GetObject("NUMBER_RED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NUMBER_YELLOW {
            get {
                object obj = ResourceManager.GetObject("NUMBER_YELLOW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Panda {
            get {
                object obj = ResourceManager.GetObject("Panda", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Peacock {
            get {
                object obj = ResourceManager.GetObject("Peacock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Pigeon {
            get {
                object obj = ResourceManager.GetObject("Pigeon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PRIZES_NUMBER {
            get {
                object obj = ResourceManager.GetObject("PRIZES_NUMBER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Rabbit {
            get {
                object obj = ResourceManager.GetObject("Rabbit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SilverShark {
            get {
                object obj = ResourceManager.GetObject("SilverShark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Swallow {
            get {
                object obj = ResourceManager.GetObject("Swallow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TIME_BACK {
            get {
                object obj = ResourceManager.GetObject("TIME_BACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TIME_NUMBER {
            get {
                object obj = ResourceManager.GetObject("TIME_NUMBER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Turntable {
            get {
                object obj = ResourceManager.GetObject("Turntable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WATER_1 {
            get {
                object obj = ResourceManager.GetObject("WATER_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WATER_10 {
            get {
                object obj = ResourceManager.GetObject("WATER_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WATER_11 {
            get {
                object obj = ResourceManager.GetObject("WATER_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WATER_12 {
            get {
                object obj = ResourceManager.GetObject("WATER_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WATER_2 {
            get {
                object obj = ResourceManager.GetObject("WATER_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WATER_3 {
            get {
                object obj = ResourceManager.GetObject("WATER_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WATER_4 {
            get {
                object obj = ResourceManager.GetObject("WATER_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WATER_5 {
            get {
                object obj = ResourceManager.GetObject("WATER_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WATER_6 {
            get {
                object obj = ResourceManager.GetObject("WATER_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WATER_7 {
            get {
                object obj = ResourceManager.GetObject("WATER_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WATER_8 {
            get {
                object obj = ResourceManager.GetObject("WATER_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WATER_9 {
            get {
                object obj = ResourceManager.GetObject("WATER_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_BRIGHT {
            get {
                object obj = ResourceManager.GetObject("WIN_BRIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_EAGLE {
            get {
                object obj = ResourceManager.GetObject("WIN_EAGLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_EAGLE_S {
            get {
                object obj = ResourceManager.GetObject("WIN_EAGLE_S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_GOLD_SHARK {
            get {
                object obj = ResourceManager.GetObject("WIN_GOLD_SHARK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_GOLD_SHARK_S {
            get {
                object obj = ResourceManager.GetObject("WIN_GOLD_SHARK_S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_LION {
            get {
                object obj = ResourceManager.GetObject("WIN_LION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_LION_S {
            get {
                object obj = ResourceManager.GetObject("WIN_LION_S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_MONKEY {
            get {
                object obj = ResourceManager.GetObject("WIN_MONKEY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_MONKEY_S {
            get {
                object obj = ResourceManager.GetObject("WIN_MONKEY_S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_PANDA {
            get {
                object obj = ResourceManager.GetObject("WIN_PANDA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_PANDA_S {
            get {
                object obj = ResourceManager.GetObject("WIN_PANDA_S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_PEACOCK {
            get {
                object obj = ResourceManager.GetObject("WIN_PEACOCK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_PEACOCK_S {
            get {
                object obj = ResourceManager.GetObject("WIN_PEACOCK_S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_PIGEON {
            get {
                object obj = ResourceManager.GetObject("WIN_PIGEON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_PIGEON_S {
            get {
                object obj = ResourceManager.GetObject("WIN_PIGEON_S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_PRIZES {
            get {
                object obj = ResourceManager.GetObject("WIN_PRIZES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_RABBIT {
            get {
                object obj = ResourceManager.GetObject("WIN_RABBIT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_RABBIT_S {
            get {
                object obj = ResourceManager.GetObject("WIN_RABBIT_S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_SHARK_0 {
            get {
                object obj = ResourceManager.GetObject("WIN_SHARK_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_SHARK_1 {
            get {
                object obj = ResourceManager.GetObject("WIN_SHARK_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_SLIVER_SHARK {
            get {
                object obj = ResourceManager.GetObject("WIN_SLIVER_SHARK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_SLIVER_SHARK_S {
            get {
                object obj = ResourceManager.GetObject("WIN_SLIVER_SHARK_S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_SWALLOW {
            get {
                object obj = ResourceManager.GetObject("WIN_SWALLOW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WIN_SWALLOW_S {
            get {
                object obj = ResourceManager.GetObject("WIN_SWALLOW_S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
