//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DzCardClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DzCardClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ADD_SCORE {
            get {
                return ResourceManager.GetStream("ADD_SCORE", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap AUTO_START_FALSE {
            get {
                object obj = ResourceManager.GetObject("AUTO_START_FALSE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AUTO_START_TRUE {
            get {
                object obj = ResourceManager.GetObject("AUTO_START_TRUE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_ADD {
            get {
                object obj = ResourceManager.GetObject("BT_ADD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_CANCEL {
            get {
                object obj = ResourceManager.GetObject("BT_CANCEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_EXIT {
            get {
                object obj = ResourceManager.GetObject("BT_EXIT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_FOLLOW {
            get {
                object obj = ResourceManager.GetObject("BT_FOLLOW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_GIVEUP {
            get {
                object obj = ResourceManager.GetObject("BT_GIVEUP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_MAX {
            get {
                object obj = ResourceManager.GetObject("BT_MAX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_MIN {
            get {
                object obj = ResourceManager.GetObject("BT_MIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_NO1 {
            get {
                object obj = ResourceManager.GetObject("BT_NO1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_OK {
            get {
                object obj = ResourceManager.GetObject("BT_OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_OPEN_CARD {
            get {
                object obj = ResourceManager.GetObject("BT_OPEN_CARD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_PASS_CARD {
            get {
                object obj = ResourceManager.GetObject("BT_PASS_CARD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_SHOWHAND {
            get {
                object obj = ResourceManager.GetObject("BT_SHOWHAND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_SITDOWN {
            get {
                object obj = ResourceManager.GetObject("BT_SITDOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_START {
            get {
                object obj = ResourceManager.GetObject("BT_START", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BT_YES1 {
            get {
                object obj = ResourceManager.GetObject("BT_YES1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CARD {
            get {
                object obj = ResourceManager.GetObject("CARD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] CARD_CUR {
            get {
                object obj = ResourceManager.GetObject("CARD_CUR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CARD_MASK {
            get {
                object obj = ResourceManager.GetObject("CARD_MASK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap D {
            get {
                object obj = ResourceManager.GetObject("D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream FOLLOW {
            get {
                return ResourceManager.GetStream("FOLLOW", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FRAME {
            get {
                object obj = ResourceManager.GetObject("FRAME", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream GAME_END {
            get {
                return ResourceManager.GetStream("GAME_END", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GAME_LOGO {
            get {
                object obj = ResourceManager.GetObject("GAME_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream GAME_LOST {
            get {
                return ResourceManager.GetStream("GAME_LOST", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream GAME_START {
            get {
                return ResourceManager.GetStream("GAME_START", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream GAME_WARN {
            get {
                return ResourceManager.GetStream("GAME_WARN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GAME_WIN {
            get {
                object obj = ResourceManager.GetObject("GAME_WIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream GAME_WIN1 {
            get {
                return ResourceManager.GetStream("GAME_WIN1", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon GameClient {
            get {
                object obj = ResourceManager.GetObject("GameClient", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static byte[] GameClient1 {
            get {
                object obj = ResourceManager.GetObject("GameClient1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        ///// GameClient.RC2 - Microsoft Visual C++ 꼇삔殮쌈긍서돨栗都
        /////
        ///
        ///#ifdef APSTUDIO_INVOKED
        ///#error 늪匡숭꼇콘譚 Microsoft Visual C++ 긍서
        ///#endif //APSTUDIO_INVOKED
        ///
        ///
        ////////////////////////////////////////////////////////////////////////////////
        ///// 瞳늪뇹警속癎땡긍서돨栗都...
        ///
        ////////////////////////////////////////////////////////////////////////////////
        ///.
        /// </summary>
        internal static string GameClient2 {
            get {
                return ResourceManager.GetString("GameClient2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream GIVE_UP {
            get {
                return ResourceManager.GetStream("GIVE_UP", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap HUMAN {
            get {
                object obj = ResourceManager.GetObject("HUMAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LEFT {
            get {
                object obj = ResourceManager.GetObject("LEFT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MAX {
            get {
                object obj = ResourceManager.GetObject("MAX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MAX1 {
            get {
                object obj = ResourceManager.GetObject("MAX1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MID {
            get {
                object obj = ResourceManager.GetObject("MID", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream NO_ADD {
            get {
                return ResourceManager.GetStream("NO_ADD", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NUMBER {
            get {
                object obj = ResourceManager.GetObject("NUMBER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RIGHT {
            get {
                object obj = ResourceManager.GetObject("RIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SCORE {
            get {
                object obj = ResourceManager.GetObject("SCORE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream SEND_CARD {
            get {
                return ResourceManager.GetStream("SEND_CARD", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream SHOW_HAND {
            get {
                return ResourceManager.GetStream("SHOW_HAND", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SHOWHAND_COMFIRE {
            get {
                object obj = ResourceManager.GetObject("SHOWHAND_COMFIRE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SMALL_CARD {
            get {
                object obj = ResourceManager.GetObject("SMALL_CARD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TIME_ARROWHEAD {
            get {
                object obj = ResourceManager.GetObject("TIME_ARROWHEAD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TITLE {
            get {
                object obj = ResourceManager.GetObject("TITLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VIEW_BACK {
            get {
                object obj = ResourceManager.GetObject("VIEW_BACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
